---
name: Continuous integration

on:
  push:

jobs:
  main:
    runs-on: ubuntu-20.04
    name: Continuous integration
    timeout-minutes: 10

    env:
      PATH: /bin:/usr/bin:/usr/local/bin:/home/runner/.local/bin
      SUMMON_PROVIDER: /usr/local/bin/gopass

    steps:
      - uses: actions/checkout@v1

      - run: |
          sudo rm /etc/apt/sources.list.d/*.list
          sudo apt update
          sudo apt install --yes python3-wheel python3-setuptools

      - run: python3 -m pip install --requirement=requirements-dev.txt

      - run: docker-compose up --exit-code-from test
      - run: git --no-pager diff --check HEAD~100

      - uses: camptocamp/initialise-gopass-summon-action@v1
        with:
          ci-gpg-private-key: ${{secrets.CI_GPG_PRIVATE_KEY}}
          github-gopass-ci-token: ${{secrets.GOPASS_CI_GITHUB_TOKEN}}
        if: github.repository == 'camptocamp/tilecloud'
      - run: |
          summon --yaml '
              USERNAME: !var gs/ci/pypi/username
              PASSWORD: !var gs/ci/pypi/password
            ' ci/publish-pypi
        if: github.repository == 'camptocamp/tilecloud'
