---
name: Auto merge Dependabot updates

on:
  pull_request:
    types:
      - opened
      - ready_for_review
      - reopened
  workflow_run:
    workflows:
      - Continuous integration
    types:
      - completed

jobs:
  auto-merge:
    name: Auto merge Dependabot updates
    runs-on: ubuntu-latest
    steps:
      - run: echo {{ toJson(github) }}
      - run: echo {{ toJson(job) }}
      - run: echo {{ toJson(steps) }}
      - name: Auto merge
        uses: ridedott/dependabot-auto-merge-action@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_LOGIN: dependabot[bot]
